### PR TITLE
WIP: Exception in Excon on non-OK status code

### PR DESCRIPTION
**Pull request by mathias**
@djcp @jessieay I couldn't find Rollbar exceptions for failures to PATCH config, and it turns out that the Excon wasn't erroring out.

This adds expectations on a success HTTP status code, but it breaks things. I just want to check quick with you (perhaps on a call?) that the tests that are failing are set up with the data and stubs/mocks we'd expect.

### CODE REVIEW

**Comment by mathias** [comment]
Any reason not to use Webmock in this project?

**Comment by jessieay** [comment]
@mathias we are using webmock https://github.com/heroku/sudo-sandwich/blob/ffd8e9e01b190620ae7a96cd5a292a149e42e9d1/spec/rails_helper.rb

**Comment by mathias** [comment]
Ah, I wasn't familiar that you can provide Sinatra apps as Webmocks. That's cool!

**Comment by mathias** [comment]
I think if I want to test both happy path and failure case, for HTTP requests, it might be quicker to just build out webmock responses in each test context. Otherwise, we'll have a lot of extra "support" code outside the tests to maintain and understand -- I missed how the Sinatra apps were hooked up, or that they existed.

Would you be OK with me taking a stab at moving all the webmocks into the test contexts for them? Typically when I do this, I do write some methods that help to make it quicker (This is just made up, not coming from an existing codebase, so it might not be 100% right) -- 
```
stub_request(:any, 'www.example.com').
      to_return(:body => 'blah', :status => 200)
```
in a `before` or `it` becomes:

```
# in spec/support/http_stubs.rb:
def stub_example_service!(overrides)
  response_method = overrides.delete(:method) || :any

  response_options = { body: 'blah', status: 200}.merge(overrides)

  stub_request(response_method).to_return(response_options)
end

# in my test file:
before do
  stub_example_service!
end

# for a failure:
before do
  stub_example_service!(body: MultiJson.encode({ error: 'unauthorized' }), status: 401)
end
```

**Comment by jessieay** [comment]
@mathias stubbing in-line can make sense for unit tests. I usually keep a sinatra fake around for integration tests but perhaps we don't need to do that in this app: https://robots.thoughtbot.com/how-to-stub-external-services-in-tests#create-a-fake-hello-sinatra

def feel free to take a stab, happy to look at any and all PRs

**Pull request closed without merging**
